services:
  postgres:
    image: postgres:16-alpine
    container_name: ai-powered-search-postgres
    networks:
      - search
    environment:
      POSTGRES_DB: chatmemory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  solr:
    image: solr:9.10.0-slim
    container_name: ai-powered-search-solr
    ports:
      - "8983:8983"
    networks:
      - search
    environment:
      ZK_HOST: "zoo:2181"
      SOLR_HEAP: "1g"
    depends_on:
      - zoo
    volumes:
      - solr_data:/var/solr
      - ./mydata:/mydata
      - ./init-solr.sh:/init-solr.sh
      - ./solr-config:/opt/solr-config
    command: [ "bash", "/init-solr.sh" ]

  zoo:
    image: zookeeper:3.9
    container_name: ai-powered-search-zookeeper
    networks:
      - search
    environment:
      ZOO_4LW_COMMANDS_WHITELIST: "mntr,conf,ruok"

volumes:
  postgres_data:
  solr_data:

networks:
  search:
    driver: bridge